name: Browser Tests

# **What it does**: This runs our browser tests on pull requests.
# **Why we have it**: This is the only way we currently test our browser JavaScript.
# **Who does it impact**: Docs engineering, open-source engineering contributors.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.ts'
      - '**.tsx'
      - jest.config.js
      - package.json
      # In case something like eslint or tsc or prettier upgrades
      - package-lock.json
      # Ultimately, for debugging this workflow itself
      - .github/workflows/browser-test.yml

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 16.14.x
          cache: npm

      - name: Install dependencies
        env:
          # This makes it so the puppeteer npm package doesn't bother
          # to download a copy of chromium because it can use
          # `$PUPPETEER_EXECUTABLE_PATH` from the ubuntu Action container.
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: npm ci --include=optional

      - name: Cache nextjs build
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}

      - name: Run build script
        run: npm run build

      - name: Run browser-test
        run: npm run browser-test
