name: Triage new pull requests

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  pull_request_target:
    types:
      - reopened
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  triage_pulls:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Label new pull requests with 'triage'
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'triage'
