name: Triage new issues

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  issues: write

jobs:
  triage_issues:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Label new issues with 'triage'
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'triage'
